version: "3"

services:
  passwordapi:
    image: "dfernandez11/ejercicio04:0.1"
    expose:
      - "8080"
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - passwordapi
    ports:
      - "8081:8081"
