apiVersion: v1
kind: Pod
metadata:
  name: secret-env-pod
spec:
  containers:
  - name: telegrambot
    image: nicopaez/telegrambot:0.0.7
    env:
      - name: TELEGRAM_TOKEN
        valueFrom:
          secretKeyRef:
            name: mysecret
            key: telegramtoken
  restartPolicy: Never
