apiVersion: apps/v1
kind: Deployment
metadata:
  name: telegrambot
  labels:
    app: telegrambot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: telegrambot
  template:
    metadata:
      labels:
        app: telegrambot
    spec:
      containers:
      - name: pingapp
        image: nicopaez/telegrambot:0.0.7
        env:
          - name: TELEGRAM_TOKEN
            valueFrom:
              secretKeyRef:
                name: mysecret
                key: telegramtoken
